### ISSUE TITLE
v3.5

### ISSUE THREAD

**Issue by FredericaBernkastel** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#20]
## ★ DGAdmin v3.5 release TODO ★

**Issues:** 
 - [x] #14: Change map & mode title in the server list
 - [x] #16: `!ft 7` Glowing bodies
 - [x] #17: functionality to disable custom team names/icons
 - [x] #18: DSR settings interface 
 - [x] #21: Server command overflow

**Feature:**
 - [x] **`Deferred properties`**
 - [x] **`    --> Dynamic properties`** (issue #18)
 - [x] `    ----> antiweaponhack` driven by DSR
 - [x] **`Unlimited ammo`**
 - [x] `settings_timed_messages`

**Commands:**
 - [x] `!kill *all*`
 - [x] `!weapon`
 - [x] `!fx`
 - [x] `!cdvar --save` and `!cdvar --reset` (personalplayerdvars)
 - [x] `!votecancel`
 - [x] `!foreach <includeself> <command> --> !foreach <*filter*> <command>`
 - [x] `!frfc <*filter*> <command> <--> !foreach <*filter*> fc <player> <command>`
 - [x] `!yell <player|all> <message> --> !yell <player | *filter*> <message>`
 - [x] `!freeze <player> --> !freeze <player | *filter*>`
 - [x] `!unfreeze <player> --> !unfreeze <player | *filter*>`
 - [x] `!mute <player> --> !mute <player | *filter*>`
 - [x] `!unmute <player> --> !unmute <player | *filter*>`
 - [x] `!teleport <player1> <player2> --> !teleport <player1 | *filter*> <player2>`
 - [x] `!ac130 <all | <player>> [-p] --> !ac130 <player | *filter*> [-p]`
 - [x] `!rotatescreen <player> <degree> --> !rotatescreen <player | *filter*> <degree>`
 - [x] `!weapon <player> <raw weapon string> [-t] --> !weapon <player | *filter*> <raw weapon string> [-t]`
 - [x] `!dsrnames` (issue #17)
 - [x] `!unlimitedammo <on/off>`
 - [x] Restrict nested `!foreach` (unuseful, possible to crash server)
 - [x] Extend players Set filters: 
`*all*, *allies*, *enemies*, *alive*, *me*, *regex*, their complements, intersections, etc.`
 - [x] `settings_disabled_commands`
 - [x] hardcoded `«banned»` or `«sucker»` group. This group is useful to restrict any command to player.

**Bugfix:**
 - [x] `!clankick <sender>` placeholder
 - [x] `!pban` is deprecated
 - [x] `!3rdperson` fix for tekno 2.8.0.2
 - [x] `isnipe_antiweaponhack` is deprecated
 - [x] `isnipe_antinoscope` is deprecated
 - [x] `settings_enable_misccommands` is deprecated
 - [x] `settings_enable_autofpsunlock` is deprecated
 - [x] fixed crash at `OnExitLevel::xlr_database.Save`
 - [x] fixed crash at `!votekick`
****
 - [x] Update documentation
![nipaa~ =^_^=](https://raw.githubusercontent.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/master/doc/img/h_1474103025_2152881_1cc4d9128b.gif)

**Comment by manuuuuuuu** [comment]
Hi :v I would like to see
!aimbot
!wallhack
!name
!prestige

**Comment by FredericaBernkastel** [comment]
@manuuuuuuu 
No naba :stuck_out_tongue_closed_eyes: 
Use Barata's Multihack v1.2 for this

**Comment by manuuuuuuu** [comment]
:((

**Comment by FredericaBernkastel** [comment]
[`https://teknogods.com/phpbb/viewtopic.php?f=76&t=38671`](https://teknogods.com/phpbb/viewtopic.php?f=76&t=38671)
